/// Current learning item used by Student Studio to resume progress.
class ContinueLearningItem {
  final String audiobookId;
  final String audiobookTitle;
  final String chapterId;
  final String chapterTitle;
  final int progressPercentage;
  final DateTime? lastPlayedAt;

  const ContinueLearningItem({
    this.audiobookId = '',
    this.audiobookTitle = '',
    this.chapterId = '',
    this.chapterTitle = '',
    this.progressPercentage = 0,
    this.lastPlayedAt,
  });

  static const empty = ContinueLearningItem();

  bool get hasProgress => audiobookId.trim().isNotEmpty;

  Map<String, dynamic> toJson() {
    return {
      'audiobook_id': audiobookId,
      'audiobook_title': audiobookTitle,
      'chapter_id': chapterId,
      'chapter_title': chapterTitle,
      'progress_percentage': progressPercentage,
      'last_played_at': lastPlayedAt?.toIso8601String() ?? '',
    };
  }
}

/// Aggregated learning activity metrics for Student Studio.
class LearningAnalytics {
  final int studyMinutes;
  final double studyHours;
  final int sessions;
  final double averageMinutesPerSession;
  final int completedChapters;
  final int masteredChapters;
  final int masteryPercentage;
  final int quizCompleted;
  final int averageQuizScore;
  final int flashcardsStudied;
  final int audioSecondsListened;
  final int audioMinutesListened;
  final int audiobooksStarted;

  const LearningAnalytics({
    this.studyMinutes = 0,
    this.studyHours = 0,
    this.sessions = 0,
    this.averageMinutesPerSession = 0,
    this.completedChapters = 0,
    this.masteredChapters = 0,
    this.masteryPercentage = 0,
    this.quizCompleted = 0,
    this.averageQuizScore = 0,
    this.flashcardsStudied = 0,
    this.audioSecondsListened = 0,
    this.audioMinutesListened = 0,
    this.audiobooksStarted = 0,
  });

  static const empty = LearningAnalytics();

  Map<String, dynamic> toJson() {
    return {
      'study_minutes': studyMinutes,
      'study_hours': studyHours,
      'sessions': sessions,
      'average_minutes_per_session': averageMinutesPerSession,
      'completed_chapters': completedChapters,
      'mastered_chapters': masteredChapters,
      'mastery_percentage': masteryPercentage,
      'quiz_completed': quizCompleted,
      'average_quiz_score': averageQuizScore,
      'flashcards_studied': flashcardsStudied,
      'audio_seconds_listened': audioSecondsListened,
      'audio_minutes_listened': audioMinutesListened,
      'audiobooks_started': audiobooksStarted,
    };
  }
}

/// Deterministic recommendation generated by the Learning Engine.
class LearningRecommendation {
  final String id;
  final String title;
  final String description;
  final String type;
  final int priority;
  final String sourceId;

  const LearningRecommendation({
    required this.id,
    required this.title,
    required this.description,
    this.type = 'general',
    this.priority = 3,
    this.sourceId = '',
  });

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'type': type,
      'priority': priority,
      'source_id': sourceId,
    };
  }
}

/// Lightweight badge/achievement for Student Studio.
class Achievement {
  final String id;
  final String title;
  final String description;
  final bool unlocked;
  final DateTime? unlockedAt;
  final int progress;
  final int target;

  const Achievement({
    required this.id,
    required this.title,
    required this.description,
    this.unlocked = false,
    this.unlockedAt,
    this.progress = 0,
    this.target = 1,
  });

  double get completionRatio {
    if (target <= 0) return unlocked ? 1 : 0;
    return (progress / target).clamp(0, 1);
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'unlocked': unlocked,
      'unlocked_at': unlockedAt?.toIso8601String() ?? '',
      'progress': progress,
      'target': target,
    };
  }
}

/// Consecutive study-day summary.
class LearningStreak {
  final int currentStreakDays;
  final int bestStreakDays;
  final DateTime? lastStudyDate;
  final List<DateTime> studyDates;

  const LearningStreak({
    this.currentStreakDays = 0,
    this.bestStreakDays = 0,
    this.lastStudyDate,
    this.studyDates = const [],
  });

  static const empty = LearningStreak();

  Map<String, dynamic> toJson() {
    return {
      'current_streak_days': currentStreakDays,
      'best_streak_days': bestStreakDays,
      'last_study_date': lastStudyDate?.toIso8601String() ?? '',
      'study_dates': studyDates.map((date) => date.toIso8601String()).toList(),
    };
  }
}

/// Rule-based student profile summary for dashboards and coaching.
class StudentIntelligence {
  final List<String> strengths;
  final List<String> weaknesses;
  final List<String> strongCompetencies;
  final List<String> weakCompetencies;
  final String risk;
  final String level;
  final int masteryPercentage;
  final List<LearningRecommendation> recommendations;

  const StudentIntelligence({
    this.strengths = const [],
    this.weaknesses = const [],
    this.strongCompetencies = const [],
    this.weakCompetencies = const [],
    this.risk = 'Sin datos',
    this.level = 'Inicial',
    this.masteryPercentage = 0,
    this.recommendations = const [],
  });

  static const empty = StudentIntelligence();

  Map<String, dynamic> toJson() {
    return {
      'strengths': strengths,
      'weaknesses': weaknesses,
      'strong_competencies': strongCompetencies,
      'weak_competencies': weakCompetencies,
      'risk': risk,
      'level': level,
      'mastery_percentage': masteryPercentage,
      'recommendations': recommendations.map((item) => item.toJson()).toList(),
    };
  }
}
