-- Durable persistence for StudyBook AI production workloads.
-- Apply only after reviewing the dry-run/backfill inventory in release docs.

begin;

create extension if not exists vector with schema extensions;

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id text not null,
  chunk_index integer not null check (chunk_index >= 0),
  page_number integer check (page_number is null or page_number > 0),
  content text not null check (length(content) > 0),
  embedding extensions.vector(1536) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, document_id, chunk_index)
);

create index if not exists document_chunks_owner_document_idx
  on public.document_chunks (user_id, document_id);

create index if not exists document_chunks_embedding_hnsw_idx
  on public.document_chunks
  using hnsw (embedding extensions.vector_cosine_ops);

create table if not exists public.certificates (
  certificate_id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_name text not null default '',
  student_code text not null default '',
  course_name text not null default '',
  average text not null default '',
  period text not null default '',
  recognition_type text not null default 'certificate',
  issued_at timestamptz not null default now(),
  status text not null default 'valid'
);

create index if not exists certificates_owner_idx
  on public.certificates (user_id, issued_at desc);

alter table public.document_chunks enable row level security;
alter table public.certificates enable row level security;

revoke all on public.document_chunks from public, anon, authenticated;
revoke all on public.certificates from public, anon, authenticated;
grant all on public.document_chunks to service_role;
grant all on public.certificates to service_role;
grant usage, select on sequence public.document_chunks_id_seq to service_role;

do $$
begin
  if exists (
    select 1
    from (values
      ('document_chunks', 'user_id'),
      ('document_chunks', 'document_id'),
      ('document_chunks', 'chunk_index'),
      ('document_chunks', 'content'),
      ('document_chunks', 'embedding'),
      ('certificates', 'certificate_id'),
      ('certificates', 'user_id'),
      ('certificates', 'status')
    ) as required_column(table_name, column_name)
    where not exists (
      select 1
      from information_schema.columns column_info
      where column_info.table_schema = 'public'
        and column_info.table_name = required_column.table_name
        and column_info.column_name = required_column.column_name
    )
  ) then
    raise exception 'Durable persistence schema is missing required columns.';
  end if;
end
$$;

create or replace function public.match_studybook_document_chunks(
  p_user_id uuid,
  p_query_embedding extensions.vector(1536),
  p_document_ids text[],
  p_match_count integer
)
returns table (
  document_id text,
  chunk_index integer,
  page_number integer,
  content text,
  metadata jsonb,
  distance double precision
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    chunk.document_id,
    chunk.chunk_index,
    chunk.page_number,
    chunk.content,
    chunk.metadata,
    (chunk.embedding <=> p_query_embedding)::double precision as distance
  from public.document_chunks chunk
  where chunk.user_id = p_user_id
    and (p_document_ids is null or chunk.document_id = any(p_document_ids))
  order by chunk.embedding <=> p_query_embedding
  limit greatest(1, least(coalesce(p_match_count, 5), 100));
$$;

revoke all on function public.match_studybook_document_chunks(
  uuid, extensions.vector, text[], integer
) from public, anon, authenticated;
grant execute on function public.match_studybook_document_chunks(
  uuid, extensions.vector, text[], integer
) to service_role;

insert into storage.buckets (id, name, public)
values ('studybook-private-artifacts', 'studybook-private-artifacts', false)
on conflict (id) do update set public = false;

commit;
