-- StudyBook AI core schema for reproducible Supabase environments.
-- This migration is additive and intentionally contains no destructive DDL.

begin;

create extension if not exists pgcrypto with schema extensions;

create or replace function public.studybook_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end
$$;

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Workspace',
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  document_id text not null,
  document_name text not null default '',
  filename text,
  file_url text not null default '',
  summary text not null default '',
  audio_url text not null default '',
  storage_bucket text,
  storage_path text,
  file_path text,
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  uploaded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, document_id)
);

create table if not exists public.study_results (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id text not null,
  type text not null,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, document_id, type)
);

create table if not exists public.audiobooks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id text not null,
  file_name text not null,
  chapters jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, document_id)
);

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  document_id text,
  title text not null default 'Nuevo chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  role text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  plan text not null default 'free',
  subscription_status text,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  plan text not null default 'free',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.educator_courses (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  code text not null default '',
  section text not null default '',
  period text not null default '',
  is_active boolean not null default false,
  program_document_id text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.educator_students (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null default '',
  name text not null,
  student_id text not null default '',
  email text not null default '',
  phone text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.educator_attendance (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null default '',
  student_id text not null default '',
  attendance_date date not null,
  status text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.educator_gradebook (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null default '',
  student_id text not null default '',
  assessment_name text not null default '',
  score numeric not null default 0,
  max_score numeric not null default 0,
  weight numeric,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.educator_question_banks (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null default '',
  title text not null default 'Banco de preguntas',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.educator_rubrics (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null default '',
  title text not null default 'Rubrica',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists workspaces_owner_created_idx
  on public.workspaces (user_id, created_at desc);
create index if not exists documents_owner_uploaded_idx
  on public.documents (user_id, uploaded_at desc);
create index if not exists documents_workspace_idx
  on public.documents (workspace_id);
create index if not exists study_results_owner_updated_idx
  on public.study_results (user_id, updated_at desc);
create index if not exists audiobooks_owner_updated_idx
  on public.audiobooks (user_id, updated_at desc);
create index if not exists chats_owner_created_idx
  on public.chats (user_id, created_at desc);
create index if not exists messages_chat_created_idx
  on public.messages (chat_id, created_at);
create index if not exists usage_events_owner_type_created_idx
  on public.user_usage_events (user_id, event_type, created_at desc);
create index if not exists educator_courses_owner_idx
  on public.educator_courses (user_id);
create index if not exists educator_students_owner_idx
  on public.educator_students (user_id);
create index if not exists educator_attendance_owner_idx
  on public.educator_attendance (user_id);
create index if not exists educator_gradebook_owner_idx
  on public.educator_gradebook (user_id);
create index if not exists educator_question_banks_owner_idx
  on public.educator_question_banks (user_id);
create index if not exists educator_rubrics_owner_idx
  on public.educator_rubrics (user_id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'workspaces', 'documents', 'study_results', 'audiobooks', 'chats',
    'user_subscriptions', 'educator_courses', 'educator_students',
    'educator_attendance', 'educator_gradebook',
    'educator_question_banks', 'educator_rubrics'
  ] loop
    execute format(
      'drop trigger if exists studybook_set_updated_at on public.%I',
      table_name
    );
    execute format(
      'create trigger studybook_set_updated_at before update on public.%I '
      'for each row execute function public.studybook_set_updated_at()',
      table_name
    );
  end loop;
end
$$;

commit;
